# Generated by Django 2.2.2 on 2019-08-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ccmm', models.CharField(max_length=5)),
                ('ticket', models.CharField(max_length=10)),
                ('analista', models.EmailField(max_length=254)),
                ('resumen', models.CharField(max_length=100)),
                ('asignatario', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('grupo_resolutor', models.CharField(max_length=20)),
                ('fecha_derivacion', models.DateField()),
                ('solucionable_cau', models.CharField(max_length=2)),
            ],
        ),
    ]
