# Generated by Django 2.2.2 on 2019-08-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['asignatario'], 'verbose_name': 'Tickets', 'verbose_name_plural': 'Tickets'},
        ),
    ]
