# Generated by Django 2.2.2 on 2019-08-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190805_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ccmm',
            field=models.CharField(choices=[('ITA', 'ITA'), ('ITO', 'ITO')], default='ITA', max_length=5),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('AB', 'Abierto'), ('CE', 'Cerrado')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solucionable_cau',
            field=models.CharField(choices=[('Si', 'SI'), ('No', 'NO')], default='No', max_length=2),
        ),
    ]
