# Generated by Django 2.2.2 on 2019-08-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190807_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comentario',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='analista',
            field=models.EmailField(choices=[('afortoul-ext@adexus.cl', 'afortoul-ext@adexus.cl'), ('cpalacios-ext@adexus.cl', 'cpalacios-ext@adexus.cl'), ('fgarcia-ext@adexus.cl', 'fgarcia-ext@adexus.cl'), ('gmoreno-ext@adexus.cl', 'gmoreno-ext@adexus.cl'), ('icuevas-ext@adexus.cl', 'icuevas-ext@adexus.cl'), ('jrausseo-ext@adexus.cl', 'jrausseo-ext@adexus.cl'), ('kgomez-ext@adexus.cl', 'kgomez-ext@adexus.cl'), ('rlopez-ext@adexus.cl', 'rlopez-ext@adexus.cl'), ('rmontoya-ext@adexus.cl', 'rmontoya-ext@adexus.cl'), ('rparra-ext@adexus.cl', 'rparra-ext@adexus.cl'), ('ssepulveda-ext@adexus.cl', 'ssepulveda-ext@adexus.cl'), ('tcabello-ext@adexus.cl', 'tcabello-ext@adexus.cl'), ('usuario@bupa.cl', 'usuario@bupa.cl'), ('vithal-ext@adexus.cl', 'vithal-ext@adexus.cl'), ('yquintero-ext@adexus.cl', 'yquintero-ext@adexus.cl'), ('N2', 'N2'), ('hjouayed-ext@adexus.cl', 'hjouayed-ext@adexus.cl'), ('spadron-ext@adexus.cl', 'spadron-ext@adexus.cl'), ('mlovera-ext@adexus.cl', 'mlovera-ext@adexus.cl'), ('agarcia-ext@adexus.cl', 'agarcia-ext@adexus.cl'), ('asegura-ext@adexus.cl', 'asegura-ext@adexus.cl')], max_length=254),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asignatario',
            field=models.CharField(choices=[('Eduardo Lizarde', 'Eduardo Lizarde'), ('Erwin Vasquez', 'Erwin Vasquez'), ('Flavio Caniumil', 'Flavio Caniumil'), ('Luis Alfaro', 'Luis Alfaro'), ('Miguel Aguilera', 'Miguel Aguilera'), ('Mauricio Alarcon', 'Mauricio Alarcon'), ('Rodrigo Lander', 'Rodrigo Lander'), ('Nurieth Vega', 'Nurieth Vega'), ('Francisco Salinas', 'Francisco Salinas'), ('Oscar Retamal', 'Oscar Retamal'), ('Constanza Aguilar', 'Constanza Aguilar'), ('Marcelo Romero', 'Marcelo Romero'), ('Francisco Labarca', 'Francisco Labarca'), ('Felipe Mella', 'Felipe Mella'), ('Fernando Sanchez', 'Fernando Sanchez'), ('Carlos Caceres', 'Carlos Caceres'), ('Oscar Muñoz', 'Oscar Muñoz'), ('Manuel Pereira', 'Manuel Pereira'), ('Claudio Reyes', 'Claudio Reyes'), ('Cesar Cortez', 'Cesar Cortez'), ('Alejandro Jeria', 'Alejandro Jeria')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('AB', 'Abierto'), ('CE', 'Cerrado'), ('EP', 'En Proceso')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='grupo_resolutor',
            field=models.CharField(choices=[('BUPA-CL-NIVEL 2', 'BUPA-CL-NIVEL 2'), ('BUPA-CL-CLINICA', 'BUPA-CL-CLINICA'), ('BUPA-CL-SOPORTE ONSITE CASA MATRIZ', 'BUPA-CL-SOPORTE ONSITE CASA MATRIZ'), ('BUPA-CL-SOPORTE ONSITE CASA MATRIZ', 'BUPA-CL-SOPORTE ONSITE CASA MATRIZ'), ('BUPA-CL-SOPORTE ONSITE MONEDA', 'BUPA-CL-SOPORTE ONSITE MONEDA'), ('ADX-CL-BUPA-SOPORTE TERRENO METROPOLITANO', 'ADX-CL-BUPA-SOPORTE TERRENO METROPOLITANO'), ('ADX-CL-BUPA-SOPORTE TERRENO REGIONAL', 'ADX-CL-BUPA-SOPORTE TERRENO REGIONAL'), ('ADX-CL-BUPA-MESA DE AYUDA', 'ADX-CL-BUPA-MESA DE AYUDA'), ('TOTALPACK', 'TOTALPACK'), ('BUPA-CL-TELECOMUNICACIONES', 'BUPA-CL-TELECOMUNICACIONES'), ('BUPA-CL-AMBIENTES COLABORATIVOS IT', 'BUPA-CL-AMBIENTES COLABORATIVOS IT'), ('BUPA-CL-SEGURIDAD DE LA INFORMACION IT', 'BUPA-CL-SEGURIDAD DE LA INFORMACION IT')], default='BUPA-CL-NIVEL 2', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resumen',
            field=models.CharField(max_length=250),
        ),
    ]
