# Generated by Django 2.2.2 on 2019-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190808_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccmm',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
