# Generated by Django 2.2.2 on 2019-08-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ccmm_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('AB', 'En Curso'), ('CE', 'Cerrado'), ('PE', 'Pendiente')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_derivacion',
            field=models.DateField(null=True),
        ),
    ]
